name: CI devops 2024

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout your GitHub code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      # Set up JDK 17 using actions/setup-java@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn clean verify --file backend-api/simple-api-student/pom.xml

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      # Build image and push backend
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend-api
          tags: ${{ secrets.USERNAME }}/tpdevops-backend-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build image and push database
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{ secrets.USERNAME }}/tpdevops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build image and push HTTP server
      - name: Build image and push HTTP server
        uses: docker/build-push-action@v3
        with:
          context: ./frontend-api
          tags: ${{ secrets.USERNAME }}/tpdevops-frontend-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}
